name: first workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
     - name: print gretting
       run: echo "Hello World"
     - name: Print goodbye 
       run: echo "Print goodbye"
    
